// Liste locale des archimonstres (source : https://dofusdb.fr/fr/database/monsters/race/78, octobre 2026, 306 noms).
// Modifiable à la main : un nom par ligne. Comparaison au nom EXACT (majuscules, accents, espaces et ponctuation ignorés) :
// « Pichakoté le Dégoutant » est un archi, « Pichakoté » non.
DM.ARCHI = [
  'Aboudbra le Porteur',
  'Abrakadnuzar',
  "Abrakanette l'Encapsulé",
  'Abrakildas le Vénérable',
  'Abrakine le Sombre',
  'Abraklette le Fondant',
  "Abrakroc l'édenté",
  'Abrinos le Clair',
  'Akaka le Souillé',
  'Alhoui le Répondeur',
  'Ameur la Laide',
  'Arabord la Cruche',
  'Arachitik la Souffreteuse',
  'Araknay la Galopante',
  'Arakule la Revancharde',
  'Bakaglace le Congelé',
  'Bambouské le Camouflé',
  "Bandapar l'Exclu",
  'Bandson le Tonitruant',
  'Barchwork le Multicolore',
  'Barebourd le Comte',
  "Bebetto l'Intellectuel",
  'Bi le Partageur',
  "Bigbadaboum l'Élémentaire",
  'Bilvoezé le Bonimenteur',
  'Bistou le Quêteur',
  'Bistou le Rieur',
  'Bitoven le Musicien',
  "Blof l'Apathique",
  'Bloporte le Veule',
  "Blordur l'Infect",
  "Blorie l'Assourdissante",
  'Bonpake le Chavireur',
  'Boombata le Garde',
  "Boostif l'Affamé",
  'Boudalf le Blanc',
  'Boudur le Raide',
  'Boufdégou le Refoulant',
  'Bouflet le Puéril',
  'Boulgourvil le Lointain',
  'Bouliver le Géant',
  'Bourde le Maladroit',
  "Brouste l'Humiliant",
  'Bulsavon le Gonflé',
  'Bworkasse le Dégoutant',
  'Bwormage le Respectueux',
  "Caboume l'Artilleur",
  'Cavordemal le Sorcier',
  "Chafalfer l'Optimiste",
  'Chafemal le Bagarreur',
  'Chaffoin le Sournois',
  'Chafmarcel le Fêtard',
  'Chafrit le Barbare',
  'Chalan le Commerçant',
  'Chamchie le Difficile',
  'Chamdblé le Cultivé',
  'Chamflay le Ballonné',
  'Chamilero le Malchanceux',
  'Chamoute le Duveteux',
  'Champayr le Disjoncté',
  "Champayt l'Odorant",
  'Champmé le Méchant',
  'Champolyon le Polyglotte',
  "Champoul l'Illuminé",
  'Chevaustine le Reconstruit',
  "Chiendanlémin l'Illusionniste",
  'Chonstip la Passagère',
  'Codenlgaz le Problème',
  "Corboyard l'Enigmatique",
  'Corpat le Vampire',
  'Crachefouxtre le Surpris',
  'Crakmitaine le Faucheur',
  'Cramikaz le Suicidaire',
  "Craquecrac l'Endurant",
  'Craquetou le Fissuré',
  'Craquetuss le Piquant',
  'Craraboss le Féérique',
  'Crathdogue le Cruel',
  'Crognan le Barbare',
  'Crok le Beau',
  "Crolnareff l'Exilé",
  'Cromikay le Néophyte',
  'Cruskof le Rustre',
  'Crusmeyer le Pervers',
  'Crustensyl le Pragmatique',
  "Crustterus l'Organique",
  'Diskord le Belliqueux',
  'Doktopuss le Maléfique',
  "Don Kizoth l'Obstiné",
  'Dragdikal le Décisif',
  'Drageaufol la Joyeuse',
  'Dragioli le Succulent',
  'Dragkouine la Déguisée',
  'Draglida la Disparue',
  'Dragminster le Magicien',
  'Dragmoclaiss le Fataliste',
  'Dragnostik le Sceptique',
  "Dragnoute l'Irascible",
  'Dragobert le Monarque',
  "Dragonienne l'Econome",
  'Dragstayr le Fonceur',
  'Dragtarus le Bellâtre',
  'Drakolage le Tentateur',
  'Draquetteur le Voleur',
  'Ecorfé la Vive',
  'Fandanleuil le Précis',
  'Fangshui la Dysorthographiée',
  'Fanlabiz le Véloce',
  'Fantoch le Pantin',
  'Fantrask la Rêveuse',
  "Farlon l'Enfant",
  'Faufoll la Joyeuse',
  'Floanna la Blonde',
  'Floriste la Cannibale',
  "Forboyar l'Enigmatique",
  'Fossamoel le Juteux',
  'Fouflay le Retombé',
  'Fourapin le Chaud',
  'Félyssion la Gourmande',
  'Garsim le Mort',
  'Gastroth la Contagieuse',
  'Gelanal le Huileux',
  'Gelaviv le Glaçon',
  "Geloliaine l'Aérien",
  "Germinol l'Indigent",
  'Ginsenk le Stimulant',
  'Gloubibou le Gars',
  'Gobstiniais le Têtu',
  'Grandilok le Clameur',
  'Grenuche la Gentille',
  'Guerrite le Veilleur',
  'Guerumoth le Collant',
  'Inopenope le Négatif',
  'Jiankor le Radoteur',
  'Kanasukr le Mielleux',
  "Kanibière l'Encordée",
  'Kannibal le Lecteur',
  'Kannisterik le Forcené',
  'Kannémik le Maigre',
  "Kaonucléair l'Instable",
  'Kapota la Fraise',
  'Kaskapointhe la Couverte',
  "Kido l'Âtre",
  "Kilimanj'haro le Grimpeur",
  'Kiroyal le Sirupeux',
  'Koakofrui le Confit',
  'Koalaboi le Calorifère',
  'Koalastrof la Naturelle',
  'Koalvissie le Chauve',
  'Koamaembair le Coulant',
  "Koamag'oel le Défiguré",
  'Koarmit la Batracienne',
  'Koaskette la Chapelière',
  'Koasossyal le Psychopathe',
  'Koko la Violente',
  'Koktèle le Secoué',
  "Kolforthe l'Indécollable",
  'Krapahut le Randonneur',
  'Krokage la Vorace',
  "Krokblanche l'Immaculée",
  'Krokcinelle la Tâchetée',
  'Krokenjambe la Tombeuse',
  'Krokette la Croustillante',
  'Krokikrisp la Céréalière',
  'Krokillage la Marine',
  'Krokillagée la Sage',
  "Krokine l'Allumeuse",
  "Krokis l'Esquissée",
  'Kroknemboure la Mousseuse',
  'Krokobure la Maudite',
  'Krokotte la Minutée',
  'Krokpit la Pilotée',
  'Krokrane la Distordue',
  'Krokrodaille la Mordante',
  'Kroktail la Désaltérante',
  'Krokue la Trompée',
  'Krokuite la Calcinée',
  "Krokée l'Entamée",
  "Kwakamole l'Appétissant",
  'Kwakolak le Chocolaté',
  'Kwakwatique le Trempé',
  'Kwaké le Piraté',
  'Kwoanneur le Frimeur',
  'Larchimaide la Poussée',
  "Larvaloeil l'Émue",
  'Larvapstrè le Subjectif',
  'Larvomatik le Propre',
  "Larvonika l'Instrument",
  'Let le Rond',
  "Lichangora l'Immaculée",
  'Madgang le Docteur',
  "Mallopiée l'Épineuse",
  "Mamakomou l'Âge",
  "Mandalo l'Aqueuse",
  'Maître Amboat le Moqueur',
  'Maître Champeur le Sabreur',
  'Maître Koantik le Théoricien',
  'Meuroup le Prêtre',
  'Milipatte la Griffe',
  'Milipussien le Géant',
  'Minoskour le Sauveur',
  "Minsinistre l'Elu",
  'Momikonos la Bandelette',
  'Mosketère le Dévoué',
  'Moumoute la Douce',
  'Mufguedin le Suprême',
  "Muloufok l'Hilarant",
  'Nakuneuye le Borgne',
  'Nelvin le Boulet',
  'Nerdeubeu le Flagellant',
  'Neufedur le Flottant',
  "Nipulnislip l'Exhibitionniste",
  'Nodkoku le Trahi',
  'Onabuémangé la Rassasiée',
  'Orfélyre le Charmeur',
  'Osuxion le Vampirique',
  "Ouashouash l'Exubérant",
  "Ouassébo l'Esthète",
  'Ouature la Mobile',
  'Ougaould le Parasite',
  'Palmbytch la Bronzée',
  'Palmiche le Serein',
  'Palmiflette le Convivial',
  'Palmito le Menteur',
  'Pantacour le Long',
  "Parapadkouï l'Émasculé",
  'Pichakoté le Dégoutant',
  'Pichdourse le Puissant',
  'Pichduitre le Totem',
  "Pichtoire l'Erudit",
  'Pioufe la Maquillée',
  'Pioukas la Plante',
  'Pioulbrineur le Mercenaire',
  'Pioulette la Coquine',
  'Pioussokrim le Délétère',
  'Pioustone le Problème',
  'Piradain le Pingre',
  "Pissdane l'Insipide",
  'Poolopo la Traditionnelle',
  'Porfavor le Quémandeur',
  'Porsalé le Râleur',
  'Preskapwal le Tendancieux',
  'Pékeutar le Tireur',
  'Pétarfoutu le Mouillé',
  'Radoutable le Craint',
  'Ramitant le Dilettante',
  "Ratlbol l'Aigri",
  'Ratéhaifaim le Professeur',
  'Rauligo le Sale',
  'Ribibi le Cher',
  "Robiolego l'Assemblé",
  "Robocoop l'Échangé",
  "Rooroku l'Imposant",
  'Rostensyl la Cuisinière',
  'Roy le Merlin',
  'Roz la Magicienne',
  "Sampi l'Eternel",
  'Sangria le Fruité',
  "Sarkastik l'Incompris",
  "Scapé l'Epée",
  'Scaramel le Fondant',
  "Scaratyn l'Huître",
  'Scarfayss le Balafré',
  "Scarouarze l'Epopée",
  "Scorpitène l'Enflammé",
  "Seripoth l'Ennemi",
  "Serpistol l'Illustre",
  'Serpistule le Purulent',
  "Souristiti l'Immortalisée",
  'Sousourizoto le Collant',
  'Sparoket le Lanceur',
  "Susbewl l'Hypocrite",
  'Tambouille le Gastronome',
  'Tikosto le Mousse',
  'Tilolo la Bien Moulée',
  "Tiwa'Missou le Gateux",
  'Tiwalpé le Dévêtu',
  'Tiwoflan le Lâche',
  "Tofuldebeu l'Explosif",
  "Tofumanchou l'Empereur",
  'Tofurapin le Pétri',
  'Tortenssia la Fleurie',
  'Torthur la Lutte',
  'Tortilleur le Coulé',
  'Tortorak le Cornu',
  'Toufou le Benêt',
  'Tour le Vice',
  'Tourbiket le Virevoletant',
  'Toutouf le Velu',
  'Tromplamor le Survivant',
  'Tronkoneuz la Tranchante',
  'Tronquette la Réduite',
  "Trooyé l'Oxydé",
  'Trukul le Lent',
  'Tsucékoi la Colporteuse',
  "Tsumani l'Inondeur",
  'Tétonée la Plantureuse',
  'Vampunor le Glacial',
  "Vétaurine l'Énergisé",
  'Wabbitud le Constant',
  'Wagnagnah le Sanglant',
  "Wara l'Amer",
  "Warkolad l'Etreinte",
  'Watdogue le Bien Nommé',
  'Wokènrôl le Danseur',
  'Étoilette la Bouchée',
];
