// Liste locale des avis de recherche (source : https://www.dofuspourlesnoobs.com/avis-de-recherche.html, octobre 2026).
// Modifiable à la main : un nom par ligne. La comparaison ignore majuscules, accents, espaces et ponctuation.
DM.WANTED = [
  "Aermyne 'Braco' Scalptaras",
  'Aigripoil',
  'Ali Grothor',
  "Amy l'empoisonneuse",
  'Anatak Diskedor',
  "Armada l'Invincible",
  'Atcham',
  'Bouflouth',
  'Bouss Baybe',
  'Brumen Tinctorias',
  'Buldalazred',
  "Carlita de l'Aguerfelde",
  'Carter le Pillard',
  'Chevalier de Glace',
  'Comte Harebourg',
  'Crasper',
  'Culbutoeuf',
  'Darma',
  'Degolas',
  'Docteur Eggob',
  'Dragodingo',
  'Dremoan',
  'Fantômayte',
  'Flasho',
  'Fojumo',
  "Fouduglen l'Écureuil",
  'Frakacia Leukocytine',
  'Fuji Givrefoux',
  'Gadoo',
  'Ganos',
  'Gein',
  "Glandaf l'Aigri",
  'Glourdorak',
  'Gobrechaun',
  'Grand Kongoku',
  'Guerrier du K.O.',
  'Guman',
  'Hin',
  'Homard Medali',
  'Hyperscampe',
  'Jérart Dupaindur',
  'Katigrou',
  "Ka'Youloud",
  'Khepricorne',
  'Le Fantôme Braïdeur',
  'Maître Boulet',
  'Marzwel le Gobelin',
  'Maxi-Malle',
  'Mekamouth',
  'Mogligli',
  'Monsieur Pingouin',
  'Morblok',
  'Mouchâme',
  "Musha l'Oni",
  'Naganita',
  'Nenufor Tilotus',
  'Nono le Wobot',
  'Ogivol Scalarcin',
  'Padgref Demoël',
  'Pantèroz',
  'Predagob',
  'Prince Marchand',
  'Psikopompe',
  'Qil Bil',
  'Roi Camole',
  'Rok Gnorok',
  "Roub' Ignolles",
  'Sam Sagaz',
  'Sans Visage',
  "Shushu Debruk'Sayl",
  'Sicogne',
  'Simbadas',
  'Takomako',
  'Tournade',
  'Trukipik',
  'Tyranne la Terrible',
  'Vashkiwi',
  'Vengeuse Masquée',
  'Viti Glourson',
  'Voldelor',
  "YeCh'Ti",
  'Zatoïshwan',
];
